from pathlib import Path

p = Path('docs/redevelopment/production-readiness-evidence-2026-09-11.md')
s = p.read_text()
s = s.replace('Latest validated code checkpoint: `879f7188f4ecf3ff1fb16409d0e10fc1350bb0ba`, `KCFC Redevelopment CI` run **#1186** / id `34582465638`, conclusion **SUCCESS**. All **57** validation/build/security steps passed.', 'Latest validated clean branch checkpoint: `8f8979b75d46d20d883876bcbd0d9ebedcc06a5a`, `KCFC Redevelopment CI` run **#1231** / id `34585740307`, conclusion **SUCCESS**. All **57** validation/build/security steps passed.')
s = s.replace('- staging Web Push runtime fail-closed enforcement requiring explicit server VAPID public/private keys before any cache/Firestore/generated-key fallback;\n', '- staging Web Push runtime fail-closed enforcement requiring explicit server VAPID public/private keys before any cache/Firestore/generated-key fallback, and re-throwing staging initialization errors before in-memory fallback key generation;\n')
s = s.replace('- staging admin mass-email broadcasts are simulation-only even when SMTP credentials are present;\n', '- staging admin mass-email broadcasts are simulation-only even when SMTP credentials are present;\n- staging public-inquiry notification and authorized inquiry-alert SMTP are suppressed/simulated so QA cannot notify the production KCFC mailbox;\n- inquiry diagnostics do not persist submitted name/email/message content or Firestore REST URLs containing API-key query parameters, and public inquiry responses do not return internal backend error detail;\n')
s = s.replace('- when `KCFC_RUNTIME_ENV=staging`, the server now refuses to start Web Push with missing explicit server VAPID keys instead of falling through to cached, Firestore, or generated credentials;\n', '- when `KCFC_RUNTIME_ENV=staging`, the server refuses missing explicit server VAPID keys and also re-throws later Web Push initialization errors before any in-memory fallback key generation;\n')
p.write_text(s)

p = Path('docs/redevelopment/staging-deployment-runbook-2026-09-11.md')
s = p.read_text()
s = s.replace('Latest validated staging-contract checkpoint: `879f7188f4ecf3ff1fb16409d0e10fc1350bb0ba`, with `KCFC Redevelopment CI` run **#1186** / id `34582465638` completing successfully with all **57** validation/build/security steps green.', 'Latest validated staging-contract checkpoint: `8f8979b75d46d20d883876bcbd0d9ebedcc06a5a`, with `KCFC Redevelopment CI` run **#1231** / id `34585740307` completing successfully with all **57** validation/build/security steps green.')
s = s.replace('When `KCFC_RUNTIME_ENV=staging`, the server itself fails closed if either explicit server VAPID key is missing; it must not fall through to cached, Firestore, or generated VAPID material.', 'When `KCFC_RUNTIME_ENV=staging`, the server itself fails closed if either explicit server VAPID key is missing. If Web Push initialization later fails for any reason, staging re-throws that error before the in-memory generated-key fallback; staging must never continue with cached, Firestore, or generated VAPID material.')
s = s.replace('For baseline staging, the admin mass-email broadcast endpoint remains simulation-only even if SMTP credentials are present. This prevents an inherited SMTP configuration from turning a staging broadcast test into live outbound mail. Single-account email verification/inquiry flows remain separate empirical QA cases and must use synthetic/test recipients under the applicable approval boundary.', 'For baseline staging, the admin mass-email broadcast endpoint remains simulation-only even if SMTP credentials are present. Public-inquiry notification email and the authorized inquiry-alert SMTP endpoint are also suppressed/simulated in staging, so inquiry QA cannot notify the production KCFC mailbox. Inquiry records may still be persisted in the isolated staging Firestore project for workflow testing. Any separately tested reply/verification email flow must use synthetic/test recipients under the applicable approval boundary.')
p.write_text(s)
