from pathlib import Path

server = Path('server.ts')
s = server.read_text()
old = '''  } catch (err: any) {\n    console.error("[WEBPUSH] Failed to initialize web-push credentials:", err);\n    const keys = webpush.generateVAPIDKeys();\n'''
new = '''  } catch (err: any) {\n    console.error("[WEBPUSH] Failed to initialize web-push credentials:", err);\n    if (runtimeEnvironment === "staging") {\n      throw err;\n    }\n    const keys = webpush.generateVAPIDKeys();\n'''
if old not in s:
    raise SystemExit('Web Push catch marker missing')
s = s.replace(old, new, 1)
server.write_text(s)

verifier = Path('scripts/verify-staging-webpush-runtime.ts')
verifier.write_text('''import fs from 'node:fs';\n\nconst source = fs.readFileSync('server.ts', 'utf8');\n\nconst required = [\n  'const envPublicKey = process.env.WEB_PUSH_VAPID_PUBLIC_KEY || process.env.VAPID_PUBLIC_KEY || "";',\n  'const envPrivateKey = process.env.WEB_PUSH_VAPID_PRIVATE_KEY || process.env.VAPID_PRIVATE_KEY || "";',\n  'if (runtimeEnvironment === "staging" && (!envPublicKey || !envPrivateKey)) {',\n  'KCFC staging safety guard: staging Web Push requires explicit WEB_PUSH_VAPID_PUBLIC_KEY and WEB_PUSH_VAPID_PRIVATE_KEY.',\n  'if (runtimeEnvironment === "staging") {\\n      throw err;\\n    }',\n];\n\nfor (const marker of required) {\n  if (!source.includes(marker)) throw new Error(`Staging Web Push runtime marker missing: ${marker}`);\n}\n\nconst stagingGuard = source.indexOf('if (runtimeEnvironment === "staging" && (!envPublicKey || !envPrivateKey))');\nconst cacheFallback = source.indexOf('if (existsSync(localKeysPath))');\nconst firestoreFallback = source.indexOf('const configRef = dbAdmin.collection("configurations").doc("webpush_vapid_keys")');\nconst outerCatch = source.indexOf('} catch (err: any) {\\n    console.error("[WEBPUSH] Failed to initialize web-push credentials:", err);');\nconst stagingRethrow = source.indexOf('if (runtimeEnvironment === "staging") {\\n      throw err;\\n    }', outerCatch);\nconst generationFallback = source.indexOf('const keys = webpush.generateVAPIDKeys();', outerCatch);\n\nif ([stagingGuard, cacheFallback, firestoreFallback, outerCatch, stagingRethrow, generationFallback].some((v) => v < 0)) {\n  throw new Error('Unable to locate staging Web Push guard/fallback ordering');\n}\nif (!(stagingGuard < cacheFallback && stagingGuard < firestoreFallback)) {\n  throw new Error('Staging Web Push key-presence guard must precede cached and Firestore fallbacks');\n}\nif (!(outerCatch < stagingRethrow && stagingRethrow < generationFallback)) {\n  throw new Error('Staging Web Push initialization errors must be re-thrown before in-memory key generation fallback');\n}\n\nconsole.log('Staging Web Push runtime boundary: PASS');\n''')
